[install] fix installation instructions for ray[default] (#35442)
The current exception message for a missing dependency is
```
RuntimeError: The Serve CLI requires the ray[default] installation: `pip install 'ray[default']``
```

The quotes and backticks are incorrect

Fix the instructions